# Generated by Django 4.2 on 2023-04-22 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carrito_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='estado',
            field=models.CharField(choices=[('N', 'NUEVO'), ('C', 'COMPRANDO'), ('F', 'FINALIZADO')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='carrito',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='detallecarrito',
            name='cantidad',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='detallecarrito',
            name='id_producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carrito_backend.producto'),
        ),
    ]
