# Generated by Django 4.2 on 2023-04-22 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito_backend', '0002_alter_carrito_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='estado',
            field=models.CharField(choices=[('N', 'NUEVO'), ('C', 'COMPRANDO'), ('F', 'FINALIZADO')], default='N', max_length=1),
        ),
    ]
