# Generated by Django 4.2 on 2023-05-18 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito_backend', '0002_carrito_estado_alter_carrito_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecarrito',
            name='descripcion',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='detallecarrito',
            name='nombre',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='detallecarrito',
            name='precio',
            field=models.FloatField(null=True),
        ),
    ]
