# Generated by Django 4.2 on 2023-04-22 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carrito_backend', '0003_carrito_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallecarrito',
            name='cantidad',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='detallecarrito',
            name='id_producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carrito_backend.producto'),
        ),
    ]
