# Generated by Django 4.2 on 2023-06-07 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito_backend', '0004_supermercado_remove_producto_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='estado',
            field=models.CharField(choices=[('NUEVO', 'NUEVO'), ('COMPRANDO', 'COMPRANDO'), ('FINALIZADO', 'FINALIZADO')], default='N', max_length=10),
        ),
    ]
