# Generated by Django 4.2 on 2023-06-07 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito_backend', '0005_alter_carrito_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='estado',
            field=models.CharField(choices=[('NUEVO', 'NUEVO'), ('COMPRANDO', 'COMPRANDO'), ('FINALIZADO', 'FINALIZADO')], default='NUEVO', max_length=10),
        ),
    ]
