FROM node:16

WORKDIR /app

# Copy package.json and package-lock.json
COPY frontend/package*.json ./

# Install dependencies with legacy peer deps to avoid breaking with source-map-loader
RUN npm install --legacy-peer-deps

# Copy the rest of the frontend code
COPY frontend/ .

# Expose React dev server port
EXPOSE 3000

# Environment for Docker hot reload
ENV HTTPS=false
ENV CHOKIDAR_USEPOLLING=true
ENV BROWSER=none

# Start React dev server
CMD ["npm", "start"]

